### PR TITLE
Update MRSK references to Kamal

### PR DESCRIPTION
**Pull request by croaky**
https://github.com/basecamp/kamal/releases/tag/v0.16.0

### CODE REVIEW

**Comment by ozgune** [comment]
Hi @croaky - thank you for opening this pull request!

I wanted to share an update as to why it's taking us a while to reply to this PR. We need to integrate a Contributor License Agreement (CLA) into our repo before accepting pull requests. We thought we'd get to it by now but worked on other priorities. So, this may take another couple of weeks. If this doesn't sound good, could you let us know?

**Comment by croaky** [comment]
Sounds good!

**Comment by furkansahin** [comment]
recheck

**Comment by croaky** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by enescakir — APPROVED** [review]

**Pull request merged**
