### PR TITLE
Add warning emoji to production prompt

### PR DESCRIPTION
**Pull request by fdr**
This can render in some situations where colors cannot.

### CODE REVIEW

**Comment by enescakir** [comment]
How is it on your terminal?
Screenshot 2023-08-22 at 22 10 00

**Comment by enescakir** [comment]
It think emojis are depend on font and terminal app. Maybe we can use more primitive signs such as `!!`, `*`.

**Comment by fdr** [comment]
Huh. 
image

**Comment by fdr** [comment]
What terminal are you using? This definitely worked for us as expected at the last outfit. The yellow sign in a composition of two unicode characters, it doesn't seem to be composing on the terminal you have

**Comment by enescakir** [comment]
I'm using [Alacritty](https://github.com/alacritty/alacritty). Looks like it has some issues with emojis on macOS. I was planning to switch [kitty](https://github.com/kovidgoyal/kitty). It might be good time move it. 
It shows emojis correctly.

Screenshot 2023-08-23 at 08 44 40

**Review by enescakir — APPROVED** [review]

**Pull request merged**
