### PR TITLE
Fix UBID constant name in loader

### PR DESCRIPTION
**Pull request by enescakir**
`RACK_ENV=production bundle exec rackup` fails because `autoload_normal` helper obligates that class name have to be CamelCase version of filename. So class name should be `Ubid` instead of `UBID`. I decided to overwrite it if it's 'Ubid' instead of rename class.

Also `lib` directory loaded anyway, no need to extra `require_relative`.

### CODE REVIEW

**Comment by enescakir** [comment]
Screenshot 2023-07-21 at 16 19 14

**Comment by fdr** [comment]
Here's a counter-proposal:

Move ubid.rb from `lib` to `__dir__` and add one line that accompanies these:

```ruby
Unreloader.autoload("#{__dir__}/clover.rb") { "Clover" }
Unreloader.autoload("#{__dir__}/clover_api.rb") { "CloverApi" }
Unreloader.autoload("#{__dir__}/clover_web.rb") { "CloverWeb" }
Unreloader.autoload("#{__dir__}/db.rb") { "DB" }
```

**Comment by fdr** [comment]
I suppose, in principle, we could even clean up the camelcase-abiding .rbs in there and run it through an algo rather than wiring in their constant names, really `DB` is the only similar exception to `UBID`.

**Comment by enescakir** [comment]
I liked your counter-proposal. I moved `ubid.rb` to `__dir__` and autoloaded manually.

**Review by fdr — APPROVED** [review]
-5 net lines?!

[Another one bites the dust](https://www.youtube.com/watch?v=eqyUAtzS_6M) :notes:

**Pull request merged**
