### PR TITLE
Switch TimestampMigrator from IntegerMigrator

### PR DESCRIPTION
**Pull request by enescakir**
IntegerMigrator doesn't allow duplicate migrations (1_foo, 1_bar). Requires manual renaming for simultaneous migrations.

Here's comparison in detail:
https://sequel.jeremyevans.net/rdoc/files/doc/migration_rdoc.html#label-Two+separate+migrators

The TimestampMigrator will be used if any filename in the migrations directory has a version greater than 20000101.

IntegerMigrator keeps version information at scheme_info table with an integer. But TimestampMigrator keeps version information at scheme_migrations tables with all filenames.

It's not backward compatible. You need to reset your database or create and fill scheme_migrations table manually, then drop scheme_info table.

### CODE REVIEW

**Comment by enescakir** [comment]
`TimestampMigrator` accepts 3 formats. Do you have personal preference @fdr?

```
# Date
20100510_create_artists.rb

# Date and Time
20100510120000_create_artists.rb

# Unix Epoch Time Integer
1273518000_create_artists.rb
```

**Comment by fdr** [comment]
I think the date only is good.

**Comment by fdr** [comment]
(let me know if the format is the date one, if so, let's commit)

**Review by fdr — APPROVED** [review]
I see the renames use date style, which is fine as duplicates are allowed.

**Pull request merged**
