### PR TITLE
Remove spaces in new lines

### PR DESCRIPTION
**Pull request by enescakir**
VS Code started to remove these spaces upon saving. We also have `trim_trailing_whitespace = true` in the `.editorconfig` file. I'm uncertain as to how these spaces were introduced, but they need to be removed.

### CODE REVIEW

**Comment by enescakir** [comment]
Okay, rhizome tests are failing. Let's see how I can fix them.

**Comment by fdr** [comment]
> VS Code started to remove these spaces upon saving. We also have `trim_trailing_whitespace = true` in the `.editorconfig` file. I'm uncertain as to how these spaces were introduced, but they need to be removed.

While we could probably do that here, it's because most editors are conservative about editing your string literals to remove spaces. It's a semantic change to the code! (which is why the tests failed)

**Comment by enescakir** [comment]
The EditorConfig plugin removes them. Others have not installed the EditorConfig plugin. @furkansahin installed it and encountered the same issue. We need to either change the string literal or remove the `trim_trailing_whitespace = true` configuration from the `.editorconfig` file.

**Comment by enescakir** [comment]
Furkan has another PR to resolve this issue. Therefore, we're closing this one.

https://github.com/ubicloud/ubicloud/pull/1090

**Pull request closed without merging**
