### PR TITLE
Push instead of single buds

### PR DESCRIPTION
**Pull request by enescakir**
When we bud a prog, we need to implement an additional label to wait it. However, when we bud a single prog, we can achieve the same functionality with pushing. Budding has the power to run multiple concurrent progs.

Net -91 lines 🔥

### CODE REVIEW

**Review by fdr — APPROVED** [review]
Maybe there's hope for "push" after all. Would it be further streamlined if we changed "push"'s style to use continuations rather than the retval check? (cc: @byucesoy )

**Comment by enescakir** [comment]
I have a branch for continues push 😀 Not created a PR yet.   I'm finishing tests for it

**Comment by fdr** [comment]
> I have a branch for continues push 😀 Not created a PR yet. I'm finishing tests for it

:exploding_head:

**Comment by enescakir** [comment]
It's not yet complete, but welcome to your feedbacks

https://github.com/ubicloud/ubicloud/pull/1193

**Review by furkansahin — APPROVED** [review]

**Pull request merged**
