### PR TITLE
Remove use of Helsinki as default

### PR DESCRIPTION
**Pull request by byucesoy**
To complete the removal of the Helsinki region, we also need to create a new E2E tests host in hetzner-fsn1. However, it is not urgent as the current host would think that it is in hetzner-fsn1 anyway and continue to work.

### CODE REVIEW

**Comment by aamederen** [comment]
:shipit:

**Comment by fdr** [comment]
Probably need to phase this patch, to ship
1) change test default fixture
2) prevent new allocations
3) <after no dependency> no more fsn1 code

**Review by fdr — COMMENTED** [review]
clearing my review queue until we're ready to ship it in phases.

**Comment by byucesoy** [comment]
> Probably need to phase this patch, to ship
> 
> 1. change test default fixture
> 2. prevent new allocations
> 3. after no dependency in prodcution, no more hel1 code

I changes this PR so that we only
- Start to default to hetzner-fsn1 in the places where we default to a region
- Updated tests to use non-helsinki regions.

We still display Helsinki as an option to user. I'll remove that option after #2/#3 is completed.

**Review by fdr — APPROVED** [review]

**Pull request merged**
