### PR TITLE
Add setup_info file to the runners for display on the GitHub UI

### PR DESCRIPTION
**Pull request by enescakir**
When you run a job on GitHub-hosted runners, information about the image can be found under the "Set up job" tab. However, this data is not available for self-hosted runners. I was curious about how GitHub-hosted runners accomplished this. After some reverse engineering, I discovered that they use the command `cp /imagegeneration/imagedata.json /home/runner/actions-runner/.setup_info` to populate this data. I have implemented this for our runners as well.

Additionally, I have included more details about the Ubicloud environment. This enhancement aids in better identifying the underlying runner.

**GitHub-hosted runners:**
Screenshot 2023-12-28 at 22 46 35

**Self-hosted runners:**
Screenshot 2023-12-28 at 22 46 48

**Ubicloud managed runners with this PR:**
Screenshot 2024-01-24 at 14 17 50

### CODE REVIEW

**Comment by furkansahin** [comment]
Is the information regarding `Image Release` correct? Should we also link to our pipeline?

**Comment by enescakir** [comment]
> Is the information regarding `Image Release` correct? Should we also link to our pipeline? Not meaning we should do, I am also trying to learn the ubicloud image pipeline and the github repo relationship.

Our repository is currently private, but we plan to open-source it soon. However, this link also works for us. We are using the same version as the official GitHub repository.

**Comment by fdr** [comment]
Any chance you can link a relevant console page (if there is one), either to a roll-up of all runner activity for the customer or this runner in particular, or both? Might be a good place to hang diagnostics not easily conveyed in-band of the github runner text.

**Comment by enescakir** [comment]
> Any chance you can link a relevant console page (if there is one), either to a roll-up of all runner activity for the customer or this runner in particular, or both? Might be a good place to hang diagnostics not easily conveyed in-band of the github runner text.

We have a page dedicated to all runners, but we currently lack individual pages for specific runners. I have added the "Console URL". The domain was hardcoded because the respirate isn't aware of the domain.

**Review by fdr — APPROVED** [review]

**Comment by fdr** [comment]
Huh we should probably add a "self" config for that. nevertheless...

**Review by byucesoy — APPROVED** [review]

**Pull request merged**
